apiVersion: v1
kind: Service
metadata:
  name: string-manipulator-api
spec:
  selector:
    app: string-manipulator-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort