# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: StringManipulator CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
#    - name: Set up Docker
#      uses: docker/setup-docker@v2
#      with:
#        docker-layer-caching: true
    - name: Docker Login
      run: docker login -u abhinana -p Abhinav1#
#    - name: Build and Push Docker Image
#      run: |
#        docker build -t abhinana/spring-manipulator-api:latest
#        docker login -u abhinana -p Abhinav1#
#        docker push abhinana/spring-manipulator-api:latest
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v6.2
      with:
        image: registry-url.io/abhinana/spring-manipulator-api
        tags: latest
        registry: registry-url.io
        dockerFile: Dockerfile
#        username: abhinana
#        password: ${{ secrets.DOCKER_PASSWORD }}
        addLatest: false
        pushImage: true
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64
        JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
